  version: '3.7'

  services:

    springboot:
      image: yisc/springboot
      container_name: springboot
      ports:
        - "8080:80"
      depends_on:
        - mysql
        - redis
        - elasticsearch   # Redis 서비스에 의존성 추가
      restart: on-failure

    mysql:
      image: yisc/mysql-8.0
      container_name: mysql
      ports:
        - "3307:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: beatbuddy
      volumes:
        - /home/ubuntu/databases/mysql/beatbuddy:/var/lib/mysql

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13  # Elasticsearch 7.17.13 이미지 사용
      container_name: elasticsearch
      environment:
        - discovery.type=single-node
      ports:
        - 9200:9200 # https
        - 9300:9300 # tcp
    redis:
      image: yisc/redis
      container_name: redis
      expose:
        - "6379"

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
          - '2181:2181'
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
          - '9092:9092'
        environment:
          KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock