
version: '3.7'

services:

  springboot:
    image: yisc/springboot
    container_name: springboot
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: on-failure

  mysql:
    # 마운트 코드 작성
    image: yisc/mysql-8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BBdb
    volumes:
      - /home/ubuntu/databases/mysql/beatbuddy:/var/lib/mysql
