ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
#RUN logstash-plugin install logstash-input-jdbc --version 4.3.18

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
