name: CD

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master" ,"develop" ]
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker rm -f $(docker ps -qa)
            sudo docker pull yisc/springboot
            # sudo docker pull yisc/mysql-8.0 (선택적으로 필요한 경우 활성화)
            sudo docker-compose up -d
            sudo docker image prune -f
