name: CICD

on:
  push:
    branches: [ "master","develop" ]
  pull_request:
    branches: [ "master" ,"develop" ]
# test cicd 3
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Make application.properties
        run: |
          cd ./src/main/resources
          touch ./application.properties
          echo "${{ secrets.PROPERTIES }}" > ./application.properties
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test


      - name: Build Redis Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker build -f docker/redis/Dockerfile -t yisc/redis .
          docker push yisc/redis

      - name: Docker build & push to docker repo
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker build -f docker/springboot/Dockerfile -t yisc/springboot .
          docker push yisc/springboot

  deploy:

    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
#
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo  docker rm -f springboot
            sudo docker pull yisc/springboot
            sudo ./docker-elk/docker-compose up -d
            sudo docker image prune -f
